### PR TITLE
add trigger options for popover : none & contextmenu

### PR DESCRIPTION
**Pull request by squat80**
Hi 
i was trying to use vue-strap components in my project but found myself somewhat blocked by the choice of triggering event (only click, hover & focus)

so i added contextmenu (my actual need, right clicking in an input field or a button) (which also required to prevent default event propagation) and none so that people might do whatever they need

please let me known if you require changes before accepting the pull request

thanks
David

### CODE REVIEW

**Comment by wffranco** [comment]
I think that none value is unnecessary.
And external triggering is not a common behavior, so instead of add a method, you can just use a ref when you need it:
```html
<popover title="Title" content="content" v-ref:trigger>
  <button class="btn btn-default ">Click</button>
</popover>
<button class="btn btn-default" @click="$refs.trigger.toggle()">External Trigger</button>
```
But the contextmenu is a good option. I will add it right now.

Greeting

**Comment by squat80** [comment]
the idea was if *none* of the available triggers match one's need, "none" could be used not to have any behaviour and then, yes, use a ref to control the popover in any way one would see fit
well anyway, contextmenu is my actual need so thanks!

**Comment by wffranco** [comment]
Done, check the last update.

**Comment by squat80** [comment]
hi you need to stop contextmenu events to propagate, otherwise the browser context menu will also trigger 
image

**Pull request closed without merging**
