### PR TITLE
V2 init

### PR DESCRIPTION
**Pull request by Humeira**

### CODE REVIEW

**Comment by Humeira** [comment]
Merge @wffranco [vue2 branch](https://github.com/wffranco/vue-strap/tree/vue2) in the initial `v2` branch.

**Comment by druppy** [comment]
Does this mean that we should continue on the @wffranco vue2 fork, or make a new one (still not git ninja:-) ) ?

**Comment by Humeira** [comment]
@druppy I'll let the contributors decide, I think the `v2` branch is more accessible to anyone who wants to help with the migration. (let's say if someone hasn't come across the issues where we discussed Vue 2.x migration)

**Comment by druppy** [comment]
@Humeira Sounds like a good idea, where can I signup .. I like to help make vue-strap become v2 ready soon, but I only had access to @wffranco vue2 fork.

Also, how much of the vue2 branch did you merge ?

And, are there any _contribute doc_ I need to know, or are all trying to do there best ? :-)

**Comment by Humeira** [comment]
@druppy at time of the merge, I took the latest @wffranco `vue2`. 
Unfortunately i can't find the contribution doc. 🤔

**Comment by druppy** [comment]
@Humeira soooo ... how can I help then ? make my own `v2` fork and make PR from there, continue on @wffranco `vue2` ?

In any case ... how will code be evaluated, what is the success criteria ?

Like the use of `value` and v-model, as it seems like vue2 has a more strict relation and detection regarding this (value is really a mutable value), and vue-strap may need to adjust (i tried to change Modal `value` to `show`). Also, most components visibility states need to be controlled by its parent, due to the new vue2 props nature. 

Just a few things that would be nice to know before making more fixes :-)

**Comment by wffranco** [comment]
well, i think the name are not so important but anyway I made the v2 branch

https://github.com/wffranco/vue-strap/tree/v2

@Humeira if you wanna help you can work in my branch, I can give you access.

**Comment by Humeira** [comment]
@wffranco why not bring it on the main repo?

**Comment by wffranco** [comment]
I don't want to pull the changes in the yuche tree until all work right.

**Comment by wffranco** [comment]
@yuche can you please solve the conflict between my branch and yours? I'm not able to do it, maybe a hard conflict with some update? I don't know.
Or remove the v2 and make a fork from mine.
https://github.com/wffranco/vue-strap/tree/v2

**Comment by wffranco** [comment]
merged v2 branch. set the version to 2.0.0-pre.1
Still need some fixes but working the most. I stablished vue2 as master in my fork.

**Comment by Humeira** [comment]
@wffranco can close this PR now then cause you're already merged.

**Pull request closed without merging**
