### PR TITLE
fixed datepicker

### PR DESCRIPTION
**Pull request by n-sviridenko**
* Added missing input event triggers
* Removed useless `this` that isn't always the real `this`
* Fixed incorrect month numbers (+1 on input click if format is `dd/MM/yyyy` or `dd-MM-yyyy`)

### CODE REVIEW

**Comment by squat80** [comment]
+1 please merge this (seems a better fix than mine #431 )

**Comment by n-sviridenko** [comment]
Also, am I need to push modified bundled files?

**Comment by wffranco** [comment]
you're using vue 1? your first changes looks like if you are handling events for vue 2

**Comment by tristanbes** [comment]
ping @wffranco, any news ?

**Comment by wffranco** [comment]
Check my branch: https://github.com/wffranco/vue-strap

**Pull request closed without merging**
