### PR TITLE
Datepicker support for non-US date formats

### PR DESCRIPTION
**Pull request by petercoles**
Datepicker doesn't play nicely with the date formats dd-MM-yyyy and dd/MM/yyyy commonly used outside of North America.

The constructor for the Date class can't tell these apart from MM-dd-yyyy and MM/dd/yyyy and treats them as though they were the latter leading to some minor bugs in highlighting the active date and a ton of Vue warnings if the date chosen is later than the 12th.

This PR catches these date formats and flips them round to ensure that the Date object is instantiated correctly. The Docs have also been updated to show these formats in action.

### CODE REVIEW

**Comment by w0bbes** [comment]
Please merge this pull. Fixed my issues aswell. Notations like dd-MM-yyyy won't work without this pull request.

**Comment by yuche** [comment]
Thanks.

**Comment by SteveEdson** [comment]
Can the `dist` folder be updated please, just been caught out by this bug.

Cheers!

**Comment by doonetheprune** [comment]
I have submitted a pull request with the dist folder updated #180

**Pull request merged**
