### PR TITLE
ready

### PR DESCRIPTION
**Pull request by wffranco**
The script generate an error when you call the method constructor if the value is null. Solved using instanceof.

### CODE REVIEW

**Comment by anlek** [comment]
Some of these look really awesome, but I feel like way too much changed in 1 pull request. The owner of the library would have to spend a really long time testing every change you've made or reading through a lot of the code. And if there is a small thing s/he disagrees with, they'd have to reject the whole request (as for as I'm aware). 

My 2 cents is try to make smaller changes and multiple pull requests. However, I might be totally wrong about this. Author, feel free to tell me so.

**Comment by wffranco** [comment]
anlek you're right, but in fact I make this pull request about a month ago without answer, so in the end I continue working over the same fork after that...
Right now I even care if all are rejected, when I have a little more time I will take it and make my own project, the first reason is because now I can't edit the gh-pages with my features.

**Comment by yuche** [comment]
@wffranco 
Please check your GitHub notifications. I just sent you a collaborators invite.  Please agree and do anything you think is necessary to help vue-strap better.
In the meantime I working on Vue 2.0 version.

**Comment by wffranco** [comment]
when I start to work with boostrap 4 I'll check that branch too... but right now I'm working with bt3 yet

**Pull request merged**
