### PR TITLE
fix mixed content

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This fixes mixed content issues while using Github Pages.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
@wffranco it'd be great if you'd say why you randomly closed a PR?

**Comment by wffranco** [comment]
sorry but not exactly random
if you check the code are exactly like yours
it wasn't me but somebody else do it, so no need to merge anything

**Comment by wffranco** [comment]
Sorry for that, but I thinks is unnesesary, I test it in chrome / firefox / edge and have no error.

What browser are you using?

**Comment by OmgImAlexis** [comment]
Just a tip, if you want people to keep submitting PRs, etc. it's nice to actually give a reason for closing a PR instead of just closing it and leaving the person that opened the PR/issue wondering what happened.

Visit your Github Pages via https. e.g. https://yuche.github.io/vue-strap/

screen shot 2016-09-01 at 3 00 02 pm

**Comment by OmgImAlexis** [comment]
@wffranco fixed the conflicts.

**Pull request merged**
