### PR TITLE
Enable data-toggle collapse on menuitems

### PR DESCRIPTION
**Pull request by jimbao**
elements with data-toggle="collapse" in navbar will collapse the navbar

### CODE REVIEW

**Comment by jimbao** [comment]
I believe this fixes https://github.com/yuche/vue-strap/issues/58

**Comment by wffranco** [comment]
Indeed, but 2 things:
* In default bootstrap script, collapse exist exactly for that, collapse the menu.
* If you need to handle a dropdown (in bootstrap style) you may use `data-toggle="dropdown"`. Or if you prefer you can use dropdown component instead.
* My question is: You have any reason to use `data-toggle="collapse"` in an element that don't have to collapse the menu?

**Comment by jimbao** [comment]
When using navbar on mobile devices. I want the be able to collapse the menu when the user selects a menu item. Seems like a natural behaviour. Are there other ways of achieving this. 
This seemed like to most straight forward approach to me.

**Comment by wffranco** [comment]
Mmm ok I understood your point, but I think in a better solution.

**Comment by wffranco** [comment]
Done, check the changes. Now collapse without adding the attribute, hop this work for you.

Greeting.

**Comment by jimbao** [comment]
Works great. Closing this since it's no longer needed. Thanks

**Pull request closed without merging**
