### PR TITLE
migrating vue-strap to use vue v2

### PR DESCRIPTION
**Pull request by EazyServer**
Migrated this package to use Vue2. Would you kindly accept this PR and create new release from it.
Many thanks

### CODE REVIEW

**Comment by shaoxiong789** [comment]
In version 2.0 there is no ‘ready’ hook

**Comment by sburnicki** [comment]
@yuche This PR would be really helpful!

**Comment by Markiter** [comment]
Unfortunately, I've tested it out and it's far from working. e.g Typeahead is completely broken, 
`[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"`

or using `key` as a name for a prop.

**Comment by EazyServer** [comment]
Yes, some Modules require a complete re-write to stop mutating props! such as Modal and Typeahead! but I get these errors (plus Vue2 compatibility errors) on the current stable version anyway!

**Comment by shaoxiong789** [comment]
https://github.com/yuche/vue-strap/tree/v2
This is v2 upgrade version

**Comment by buccfer** [comment]
Any update on this?

**Comment by neilsmind** [comment]
Per @shaoxiong789 message above, I think this pull request should be closed.

**Pull request closed without merging**
