### PR TITLE
Fix error date selected format dd/MM/yyyy issues #301

### PR DESCRIPTION
**Pull request by bernardo-bruning**

### CODE REVIEW

**Comment by bernardo-bruning** [comment]
Fix issue #301

**Comment by prodes** [comment]
Please add this fix to the master. 
We've tested it and it solves the problem! Thanks @bernardo-bruning @yuche

**Comment by smartpierre** [comment]
I had the same issue and this fix solved it, please merge !

**Comment by wffranco** [comment]
fix the conflict

**Pull request merged**
