### PR TITLE
A typo which causing Vue compiling error!

### PR DESCRIPTION
**Pull request by EazyServer**

### CODE REVIEW

**Comment by EazyServer** [comment]
Forgot to mention this is a 2 commits PR!
One to fix the typo and the second one suggest using 'v-html' to set the contents instead of using curly "{{}}" setter!

Apologies if you have not noticed that already!

Thanks again

**Comment by JhonMr** [comment]
The error is still after changed '{{{content}}}' to 'v-html="content"' and then rebuild the project.why?

**Comment by EazyServer** [comment]
Because the the project author has not created a release after this merge yet! I hope he/she does so soon.

**Comment by shaoxiong789** [comment]
already build and merge this!

**Comment by ricardoorellana** [comment]
Guys it seem this issue has not been fixed yet, I have tried to use Tooltip component and I got the same error `<span v-el:trigger>
    <slot></slot>
    <div v-el:popover v-if="show" style="display:block;"
      :class="['tooltip',placement]"
      :transition="effect"
    >
      <div class="tooltip-arrow"></div>
      <div class="tooltip-inner">
        <slot name="content">{{{content}}}</slot>
    </div>
    </div>
  </span>

- invalid expression: {{{content}}}


found in`

**Pull request merged**
